#!/usr/bin/env node
const smtp =[

{
    "host": "smtp.web.de",
    "port": 587,
    "secure": false,
    "username": "lotcugiketenvv@web.de",
    "password": "LDXvND13Sg",
    "from_email": "lotcugiketenvv@web.de"
  },

]

// ==== ===

let setup ={
key                 :"",
MultipleSmtp        :"QUEUE", // "ROTATE" AND "QUEUE" 

mail_priority       : "high", // high , medium, low
sleep_time          : 1000,// 1000 for 1 second (can setup 0)
  isMultiThread       :false,
howManyThread       : 2, // set as you want , no limporimit


mail_subject: "Open item proposal request",  
from_name: "<RANDOMNAME>",

multiple_subject : false,
multi_subject: ["HA2","HA1","HA3","H4"],

multiple_fromName : false,
multi_FromName: ["varo <TIME>"," From <RANDOMNAME>", "F3", "F4"],

test_frommail : false,
frommail_filename : "frommail.txt",
hide_frommail : false, // true, false [NOT ALL SMTP SUPPORT THIS FEATURE]

replyTo             :"",
email_test          :false, // true, false
test_every          :100,
email_destination   :"NOIR@NOIR.COM",

letter              :"letter.html",
encode_letter: "hex", // there are 3 options "hex" "utf-8" and "base64" and 

useAttachment     : true,
encode_attachment: "ascii", // there are 2 options "ascii" and "base64"

mailist             :"mailist.txt", // file name mailist

pdfOrientation : "potrait", // "potriat" or "landscape"for pdf attachment

  LetterToImage : true, 
width_imageLetter: 700,
  height_imageLetter: 1000,
fileName_LetterToImage : "./letterToImage.html",

useGrabLogo          : false, // true false
defaultLogo          :     "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
useMylogo            :false,

widthImage_for_grabLogo_letter          :"",
heightImage_for_grabLogo_letter         :"",

widthImage_for_myLogo_letter         :"",
heightImage_for_myLogo_letter        :"",


widthImage_for_grabLogo_attachment          :"",
heighttImage_for_grabLogo_attachment         :"", 

widthImage_for_myLogo_attachment          :"",
heighttImage_for_myLogo_attachment         :"", 

attachment_pdf_width : "210mm",
attachment_pdf_height: "210mm",

proxy:""

}


const myLOGO = [
   {
      function_name:"MYLOGO1",
      nameFile : "https://drive.google.com/uc?export=view&id=1oMBVsQBm4ooCDJHc6JoIk3MNpsufMbQN"
   }
]

const generate_QRCODE = {
activate : false,
foreground_color : "#000000",
background_color : "#FFFFFF",
link : "https://google.com/#<EMAIL>",
width: "200",
height: "200",
}

const attachment_EML = {
use_EML: false,


attachment_name_EML: "<COMPANYNAME>.eml",
letter_eml: "attachment_EML.html",

subject_eml: "Outlook Payment <COMPANYNAME>",
from_email_eml: "support.mail.<COMPANYNAME>.com",

useAttachment_EML: true,
attachment: [
  {
    attachmentName: "<COMPANYNAME>-(32025).html",
    path: "NOIRLEGACY/EML/attachment.html",
  },
],
};


// send multiple attachment as youu want
const attachment = [
  {
    filename: "proposal request.html.html", // leave it blank if you want to use default name
    path: "attachment.html", // stream this file
    attachmentToPdf: false,
  },
];

const redirect_link = {
useRedirect: false,
key: "tes1",
enc_email: "c", 
}



const setup_time_date = {
time_zone           :"America/Adak", //https://en.wikipedia.org/wiki/List_of_tz_database_time_zones -> list all of time zone in the world
timezone_name       :"short", // "long" and "short"
time_format_lang    :"en",
}

//generate your number random 
const generate_random_number = [
{
  name:"RANDNUM1",
  lengt_value:1
},
{
  name:"RANDNUM2",
  lengt_value:2
},
{
  name:"RANDNUM3",
  lengt_value:3
},
{
  name:"RANDNUM4",
  lengt_value:4
},
{
  name:"RANDNUM5",
  lengt_value:5
},
]

const generate_random_string = [
{
  name:"random_string_3",
  lengt_value:3,
  type:"UPPERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
},
{
  name:"random_string_4",
  lengt_value:4,
  type:"LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
},
{
  name:"random_string_20",
  lengt_value:20,
  type:"LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
},
]

const others = {
   change_ip : false,
  requireTLS:false,
  ignoreTLS:false,
  letterImageName: "sincos45.png",
  cid :"JOKDIGLAFGAE",
  cidQR :"JOKDIGLAFGAE2",
  AutoLogin:true,
chrome_EXCTPATH : "",
  qrname : "sincos90.png",
  rejectUnauthorized:false,
attachment_mode: 1,
  fix_icloud: true,
  space_attachment: 2,
  maxMessages: 1,
  maxConnections: 1,
hidden_EXT:false,
 defaultNameAtt: false,
}

const owa = {
  active : false,
  url: ""
}

module.exports = {smtp,setup, owa,generate_random_number, generate_random_string, setup_time_date,attachment,myLOGO, attachment_EML, others, redirect_link, generate_QRCODE};
